export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTION = "FETCH_QUESTION";
export const SAVE_QUESTION = "SAVE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const FETCH_RESULTS = "FETCH_RESULTS";
export const FETCH_QUIZZ = "FETCH_QUIZZ";
export const FETCH_QUIZZS = "FETCH_QUIZZS";
export const SAVE_QUIZZ = "SAVE_QUIZZ";
export const FETCH_QUIZZ_RESULTS = "FETCH_QUIZZ_RESULTS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTION_SUCCESS = "FETCH_QUESTION_SUCCESS";
export const SAVE_QUESTION_SUCCESS = "SAVE_QUESTION_SUCCESS";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_QUIZZ_SUCCESS = "FETCH_QUIZZ_SUCCESS";
export const FETCH_QUIZZS_SUCCESS = "FETCH_QUIZZS_SUCCESS";
export const SAVE_QUIZZ_SUCCESS = "SAVE_QUIZZ_SUCCESS";
export const FETCH_QUIZZ_RESULTS_SUCCESS = "FETCH_QUIZZ_RESULTS_SUCCESS";
export const FETCH_QUESTIONS_FAILED = "FETCH_QUESTIONS_FAILED";
export const FETCH_QUESTION_FAILED = "FETCH_QUESTION_FAILED";
export const SAVE_QUESTION_FAILED = "SAVE_QUESTION_FAILED";
export const DELETE_QUESTION_FAILED = "DELETE_QUESTION_FAILED";
export const FETCH_RESULTS_FAILED = "FETCH_RESULTS_FAILED";
export const FETCH_QUIZZ_RESULTS_FAILED = "FETCH_QUIZZ_RESULTS_FAILED";
export const FETCH_QUIZZ_FAILED = "FETCH_QUIZZ_FAILED";
export const FETCH_QUIZZS_FAILED = "FETCH_QUIZZS_FAILED";
export const SAVE_QUIZZ_FAILED = "SAVE_QUIZZ_FAILED";
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const USER_SIGN_OUT_FAILED = "USER_SIGN_OUT_FAILED";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";
export const CLEAR_SAVE_ANSWER_ERROR = "CLEAR_SAVE_ANSWER_ERROR";
export const CLEAR_SAVE_QUESTION_ERROR = "CLEAR_SAVE_QUESTION_ERROR";
export const CLEAR_SAVE_QUIZZ_ERROR = "CLEAR_SAVE_QUIZZ_ERROR";


//
export const SAVE_QUESTION_ANSWER= "SAVE_QUESTION_ANSWER";
export const SAVE_QUESTION_ANSWER_SUCCESS= "SAVE_QUESTION_ANSWER_SUCCESS";
export const SAVE_QUESTION_ANSWER_FAILED= "SAVE_QUESTION_ANSWER_FAILED";
export const FETCH_ALL_USERS= "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const CLEAR_USERS_ERROR = "CLEAR_USERS_ERROR";
//


export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const FETCH_USER = "FETCH_USER";
export const SAVE_USER = "SAVE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const SAVE_USER_FAILED = "SAVE_USER_FAILED";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

//export const ADD_ADMIN = "ADD_ADMIN";
//export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
//export const ADD_ADMIN_FAILED = "ADD_ADMIN_FAILED";


