export default {
    perspective_type:'Perspective Type',
    id:'Id',
    quizz_id:'Quizz Id',
    question_string:'Question String',
    question_label:'Label',
    question_dimension:'Dimension',
    question_direction:'Direction',
    question_meaning:'Meaning',
    min_value:'Minimum Value',
    max_value:'Maximum Value',
    dimension1:'Dimension 1',
    dimension2:'Dimension 2',
    dimension3:'Dimension 3',
    dimension4:'Dimension 4',    
    booking_text:'Bookings',
    results_text:'Results',
    quizz_text:'Quizz',
    name:'Name',    
    today_text:'Today',
    this_month_text:'Month',
    total:'Total',
    sign_in:'Sign in',
    personality_quizz:'Personality Quizz',
    email_address:'Email Address',
    password:'password',
    sign_in_error:'Sign In Error. Please check Email and Password.',
    device_type:'Device Type',
    user_type:'User Type',
    title:'Title',
    body:'Body',
    push_notification_title:'Push Notifications',
    promo_name:'Promo Name',
    description:'Description',
    start_date:'Start Date (dd/mm/yyyy)',
    end_date:'End Date (dd/mm/yyyy)',
    submit:'Submit',
    update_failed:'Update Failed',
    update:'Update',
    first_name:'First Name',
    last_name:'Last Name',
    email:'Email',
    account_approve:'Account Approved',
    quizz_active:'Active Status',
    lisence_image:'License Image',
    vehicle_number:'Vehicle Number',
    all_user:'All Users',
    no_user_match:'No Users Matched',
    no_user_matching:'No users found matching your selection.',
    dashboard_text:'Dashboard',
    quizzs_text:'Quizzs',
    questions_text:'Questions',
    users_text:'Users',
    user:'Users',
    owner:'Owners',
    admin:'Admins',
    is_admin:'Is Admin',
    logout:'Log Out',
    months:'Months',
    year:'Years',
    settings_title:'Settings',
    settings_label1:'Cash',
    quizz_active_label:'Quizz Active',
    createdAt: 'Create Date',
}